version: "3.8"

services:
  database:
    image: postgres
    restart: unless-stopped
    container_name: postgres-db
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  application:
    depends_on:
      - database
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-management-api
    ports:
      - "${SPRING_DOCKER_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url": "jdbc:postgresql://database:${POSTGRES_PORT}/${POSTGRES_DATABASE}",
             "spring.datasource.username": "${POSTGRES_USER}",
             "spring.datasource.password": "${POSTGRES_PASSWORD}",
             "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",
             "spring.jpa.hibernate.ddl-auto": "update"
           }'
    stdin_open: true
    tty: true
