services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-management-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transactions
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=testing-password
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing-password
    ports:
      - "5432:5432"