system:
  defaults:
    currency: U.S. Dollars
  gateways:
    fiscal-gateway:
      base-url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service
      max-connection-attempts: 3
      timeout-between-fetch-attempts-in-millis: 2000
      refresh-interval-in-milliseconds: 60000 # 1 minute interval between cache refreshes, testing cases
      enable-caching: true

spring:
  application:
    name: Transaction Management API
    version: 1.1
    description: Technical Challenge API
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true