system:
  defaults:
    currency: U.S. Dollars
  gateways:
    fiscal-gateway:
      base-url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service
      max-connection-attempts: 3
      timeout-between-fetch-attempts-in-millis: 2000
      refresh-interval-in-milliseconds: 60000 # 1 minute interval between cache refreshes, testing cases
      enable-caching: true

spring:
  application:
    name: Transaction Management API
    version: 1.1
    description: Technical Challenge API
  datasource:
    url: jdbc:h2:mem:transactions
    driver-class-name: org.h2.Driver
    username: admin
    password: testing-password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true